version: '2.0'
services:

    age:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: age
        environment:
            SLS_DEBUG: "*"
        volumes:
            - .:/var/age
        links:
            - age-db:age-db

    age-db:
        image: deangiberson/aws-dynamodb-local
        container_name: age-db
        expose:
            - "8000"