slot_values:
    command:
        jester:
            - clown
            - fool
            - annoyance
        yes:
        no:
    credit:
        Nick Stacey:
            - Nick
            - Nick S
    item:
        - brass key
    object:
        - door
        - west door
        - south door
        - north door
        - switch

utterances:
    HelpIntent:
        - "Help me now"