config:
    invocation_name: age test

    default_responses:
        repeat: If you want to hear that again, say "repeat".

        game_over: To start a new game, say "Alexa, start :invocation_name".

        load_game:
            description: Welcome back to AGE test. Would you like to continue where you left off? "continue game" or "restart game".
            repeat: You have 8 seconds to comply. "continue game" or "restart game".

        unhandled:
            description: I'm not sure what you mean.
            repeat: Say "help" to get some help if you don't know what to say.

        room:
            help:
                description: We're not going to help you.
                repeat: I said, we're not going to help.
            repeat: Hurry now.

        use:
            failed:
                solo: You can't use :itemNameA.
                dual: You can't use :itemNameA with :itemNameB.

        pickup:
            failed:
                description: The item ":itemName" cannot be used at this moment.
                repeat: Another repeat.
            already:
                description: You already have ":itemName".
                repeat: Another repeat.

        inspector:
            failed: You can not inspect that item at this moment.
            repeat: Hurry now.

    plugins:
        - Default/Rooms
        - Default/Flags
        - Default/Inspector
        - Default/Inventory
        - Default/StartMenu
