config:
    default_responses:
        repeat: If you want to hear that again, say "repeat".

        load_game:
            description: Welcome to back to AGE test. Would you like to continue where you left off? "yes" or "no".
            repeat: You have 8 seconds to comply. "yes" or "no".

        unhandled:
            description: I'm not sure what you mean.
            repeat: Say "help" to get some help if you don't know what to say.

        # same_state_question: What now?

        room:
            help:
                description: We're not going to help you.
                repeat: I said, we're not going to help.
            repeat: Hurry now.

        use:
            failed:
                solo: You can't use :itemNameA.
                dual: You can't use :itemNameA with :itemNameB.

        pickup:
            failed:
                description: The item ":itemName" cannot be used at this moment.
                repeat: Another repeat.
            already:
                description: You already have ":itemName".
                repeat: Another repeat.

        inspector:
            failed: You can not inspect that item at this moment.
            repeat: Hurry now.

    plugins:
        - Rooms
        - Flags
        - Inspector
        - Inventory
        - StartMenu
        - age-insult-fighting/InsultFighting
